DROP DATABASE IF EXISTS Ortopedia_BM ;
CREATE DATABASE Ortopedia_BM ;

USE Ortopedia_BM ;

CREATE TABLE  PEDIDOS(
	IDPEDIDOS 		INT PRIMARY KEY AUTO_INCREMENT
,   IDCLIENTE 		INT
,   IDVENTAS        INT
,   IDSTOCK 	    INT
,   IDEMPLEADO 		INT
,   IDPROVEEDORES   INT
,   IDCOMPRAS       INT
,   FECHA 			DATETIME
,   CANCELACION 	DATETIME DEFAULT NULL
)
COMMENT 'Registra los pedidos realizadas por los clientes'
;

CREATE TABLE PROVEEDORES(
	IDPROVEEDORES   INT PRIMARY KEY AUTO_INCREMENT
,   NOMBRE          VARCHAR(30)  DEFAULT 'PROVEEDOR'
,   APELLIDO        VARCHAR(30)  NOT NULL
,   TELEFONO        VARCHAR(11)  NOT NULL
,   CORREO          VARCHAR(100) UNIQUE NOT NULL
,   CUIT            VARCHAR(11)  UNIQUE
,   IDORTOPEDIA     INT
);

CREATE TABLE COMPRAS(
	IDCOMPRAS        INT PRIMARY KEY AUTO_INCREMENT
,   NOMBRE           VARCHAR(30) DEFAULT 'USUARIO'
,   APELLIDO         VARCHAR(30) NOT NULL
,   TELEFONO         VARCHAR(11) NOT NULL
,   CORREO           VARCHAR(100) UNIQUE NOT NULL
,   CUIT             VARCHAR(11)  UNIQUE NOT NULL
,   IDORTOPEDIA      INT
,   IDPROVEEDORES    INT
);
   
CREATE TABLE  CLIENTE(
    IDCLIENTE 		INT PRIMARY KEY AUTO_INCREMENT
,   NOMBRE 			VARCHAR(30) DEFAULT 'PARTICULAR'
,   APELLIDO        VARCHAR(30)
,   TELEFONO 		VARCHAR(11) NOT NULL
,   CORREO 			VARCHAR(100) UNIQUE NOT NULL
,   IDEMPLEADO      INT
,   CUIT            VARCHAR(11) UNIQUE NOT NULL
);

CREATE TABLE  EMPLEADO(
	IDEMPLEADO		INT PRIMARY KEY AUTO_INCREMENT
,	NOMBRE			VARCHAR(30)
,   APELLIDO        VARCHAR(30)
,	CORREO			VARCHAR(100) UNIQUE DEFAULT	'Ortopedia_BM@ventas.com'
,	TELEFONO		VARCHAR(100)
,	IDORTOPEDIA	    INT
,   IDDUEÑO         INT
,   IDSTOCK         INT
,   IDCLIENTE       INT
);

CREATE TABLE  DUEÑO(
	IDDUEÑO			INT PRIMARY KEY AUTO_INCREMENT
,	NOMBRE			VARCHAR(30)
,   APELLIDO        VARCHAR(30) NOT NULL 
,	CORREO			VARCHAR(100) UNIQUE NOT NULL DEFAULT 'Ortopedia_BM@GerenteGeneral.com'
,	TELEFONO		VARCHAR(11) NOT NULL
,	CUIT			VARCHAR(11) UNIQUE NOT NULL 
,   IDORTOPEDIA     INT
,   IDCOMPRAS       INT
);

CREATE TABLE  ORTOPEDIA(
	IDORTOPEDIA  	INT PRIMARY KEY AUTO_INCREMENT
,	NOMBRE			VARCHAR(30)
,   DIRECCION		VARCHAR(100) NOT NULL
,   CUIT            VARCHAR(11) UNIQUE NOT NULL
,   TELEFONO		VARCHAR(100) NOT NULL
,   IDSTOCK         INT
);

CREATE TABLE  VENTAS(
	IDVENTAS	INT PRIMARY KEY AUTO_INCREMENT
,	ELEMENTO	VARCHAR(100) DEFAULT 'ELEMENTO'
,   NOMBRE      VARCHAR(30)
,   APELLIDO    VARCHAR(30) NOT NULL 
,   TELEFONO    VARCHAR(11) NOT NULL
,   IDORTOPEDIA INT
);

CREATE TABLE  STOCK(
	IDSTOCK 		INT PRIMARY KEY AUTO_INCREMENT
,	IDORTOPEDIA	    INT
,	CANTIDAD		INT
,	DISPONIBILIDAD	BOOLEAN
)
COMMENT "Contiene información sobre el stock disponibles en cada Ortopedia"
;

ALTER TABLE CLIENTE
    ADD CONSTRAINT FK_CLIENTE_EMPLEADO
    FOREIGN KEY (IDEMPLEADO ) REFERENCES EMPLEADO(IDEMPLEADO);

ALTER TABLE DUEÑO
    ADD CONSTRAINT FK_DUEÑO_ORTOPEDIA
    FOREIGN KEY (IDORTOPEDIA ) REFERENCES ORTOPEDIA(IDORTOPEDIA);

ALTER TABLE DUEÑO 
    ADD CONSTRAINT FK_DUEÑO_COMPRAS
    FOREIGN KEY (IDCOMPRAS ) REFERENCES COMPRAS(IDCOMPRAS);
    

ALTER TABLE EMPLEADO
	ADD CONSTRAINT FK_EMP_ORTOPEDIA
    FOREIGN KEY (IDORTOPEDIA ) REFERENCES ORTOPEDIA(IDORTOPEDIA);
    
ALTER TABLE EMPLEADO
    ADD CONSTRAINT FK_EMP_CLIENTE
    FOREIGN KEY (IDCLIENTE ) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE EMPLEADO
    ADD CONSTRAINT FK_EMP_STOCK
    FOREIGN KEY (IDSTOCK ) REFERENCES STOCK(IDSTOCK);

ALTER TABLE COMPRAS
	ADD CONSTRAINT FK_COMPRAS_PROVEEDORES
    FOREIGN KEY (IDPROVEEDORES ) REFERENCES PROVEEDORES(IDPROVEEDORES);
    
    


ALTER TABLE STOCK
	ADD CONSTRAINT FK_STOCK_ORTOPEDIA
    FOREIGN KEY (IDORTOPEDIA ) REFERENCES ORTOPEDIA(IDORTOPEDIA);

ALTER TABLE PEDIDOS
	ADD CONSTRAINT FK_PEDIDOS_STOCK
    FOREIGN KEY (IDSTOCK ) REFERENCES STOCK(IDSTOCK);

ALTER TABLE PEDIDOS
	ADD CONSTRAINT FK_PEDIDOS_EMPLEADO
    FOREIGN KEY (IDEMPLEADO ) REFERENCES EMPLEADO(IDEMPLEADO );
    
ALTER TABLE PEDIDOS
	ADD CONSTRAINT FK_PEDIDOS_VENTAS
    FOREIGN KEY (IDVENTAS ) REFERENCES VENTAS(IDVENTAS);

ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_PEDIDOS_PROVEEDORES
    FOREIGN KEY  (IDPROVEEDORES ) REFERENCES PROVEEDORES(IDPROVEEDORES);

ALTER TABLE PEDIDOS
     ADD CONSTRAINT FK_PEDIDOS_COMPRAS
     FOREIGN KEY (IDCOMPRAS ) REFERENCES COMPRAS(IDCOMPRAS);
     
 ALTER TABLE PEDIDOS
     ADD CONSTRAINT FK_PEDIDOS_CLIENTE
     FOREIGN KEY (IDCLIENTE ) REFERENCES CLIENTE(IDCLIENTE);    
    
ALTER TABLE ORTOPEDIA
     ADD CONSTRAINT FK_ORTOPEDIA_STOCK
     FOREIGN KEY (IDSTOCK ) REFERENCES STOCK(IDSTOCK); 

SELECT 
	*
FROM INFORMATION_SCHEMA.TABLES
WHERE table_schema = "Ortopedia_BM";